### ISSUE TITLE
TODO python dalex

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEX#161]
- [x] upload package to pip
- [x] update `DALEX/python/dalex/README.md`
- [x] add `titanic` dataset 
- [x] provide access to jupyter notebooks
- [x] add preprocessed fifa20 dataset + notebook
- [ ] add examples to documentation
- [ ] generate site-documentation
- [x] add gh-actions for python 
- [x] add tests for fit methods
- [x] add tests for plot methods
- [x] fix `SettingWithCopyWarning` in `Shap.plot()`
- [x] add python NEWS.md
- [ ] [request adding the package to conda](https://docs.anaconda.com/anaconda/packages/pkg-docs/)

**Comment by pbiecek** [comment]
@hbaniecki can we close this one (if it's done)?

**Comment by hbaniecki** [comment]
sure
