### ISSUE TITLE
DRAFT: dalex v1.0

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEX#368]
Draft: what if? Potentially `v1.0` should be the next version. 

Breaking changes:
- [x] refactor modules: `instance_level` to `predict_explanations` and `dataset_level` to `model_explanations`
- [x] move arena to 'true' lowercased folder
- [x] add `plot` method and `result` attribute to `LimeExplanation` / ~consider adding `LimeWrapper`~
- [x] cord-flip `cp`  barplots (will be consistent with ema)
- [x] ~change plot titles (consistent with ema)~

To resolve:
- [x] Add or abandon pycaret https://github.com/ModelOriented/DALEX/issues/332 (comment: these are `sklearn` compatible)
- [x] Add or abandon pyspark mllib https://github.com/ModelOriented/DALEX/issues/332 (comment: abandon)
- [x] check if examples in EMA are working with dalex 1.0
- [x] add fairness to Arena

Later:
- [x] ~Finish by uploading to conda https://github.com/ModelOriented/DALEX/issues/360~

Won't be included in this release:
- support for multiclass
- `predict_diagnostics`

**Comment by pbiecek** [comment]
+ move arena to 'true' lowercased folder in https://github.com/ModelOriented/DALEX/tree/master/python/dalex/dalex

**Comment by pbiecek** [comment]
if possible, a great feature would be the option to write a pdf version of a graph.
now it is pretty hard to polish plots in postprocessing

**Comment by hbaniecki** [comment]
For me this works: 
```python 
# need pip install -U kaleido
# see https://plotly.com/python/static-image-export/

import dalex as dx
import pandas as pd
from sklearn.ensemble import AdaBoostClassifier
data = dx.datasets.load_titanic()
X = data.drop(['survived', 'embarked', 'class', 'gender'], axis=1)
y = data.survived
model = AdaBoostClassifier(random_state=0).fit(X, y)
exp = dx.Explainer(model, X, y)
pdp = exp.model_profile().plot(show=False)
pdp.write_image("temp.pdf", width=800, height=600)
```

**Comment by pbiecek** [comment]
and maybe this one:

- [ ] check if examples in EMA are working with dalex 1.0

**Comment by hbaniecki** [comment]
https://pypi.org/project/dalex/1.0.0/
